# Generated by Django 3.2.3 on 2021-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='used_technologies',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('VueJS', 'VueJS'), ('PostgreSQL', 'PostgreSQL'), ('React', 'React'), ('React Native', 'React Native'), ('Firebase', 'Firebase')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
