# Generated by Django 3.2.3 on 2021-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_used_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='used_technologies',
            field=models.CharField(max_length=500),
        ),
    ]
