# Generated by Django 3.2.3 on 2021-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
