# Generated by Django 3.2.3 on 2021-06-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
    ]
