# Generated by Django 3.2.3 on 2021-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210601_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
