# Generated by Django 3.2.3 on 2021-12-29 19:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profiledescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledescription',
            name='personal_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
